#!/bin/bash

# API Credentials
#########################################################################################
apiuser="USERNAME HERE"
apipass="PASSWORD HERE"
jssURL="URL HERE"

# Pull Serial Number from End User Device
# This is Used to Obtain Computer Name from JAMF
#########################################################################################
SERIAL=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')

# Pull Computer Device Name from JAMF
#########################################################################################
COMPUTERNAME=$(curl -H "Accept: text/xml" -sfku "${apiuser}:${apipass}" "${jssURL}/JSSResource/computers/serialnumber/${SERIAL}/subset/general" | xmllint --format - 2>/dev/null | awk -F'>|<' '/<name>/{print $3; exit}')


#API Group ID, NAME & URL Identifiers
#########################################################################################

#NONDEPprestage
GROUP_ID="###"
GROUP_NAME="NAME OF GROUP"
GROUP_URL="JSSResource/computergroups/id/${GROUP_ID}"


#XML header information, used to PUT & PULL
#########################################################################################
xmlHeader="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>"


#Add Computer to Group
#########################################################################################
GROUP_Data="<computer_group><id>${GROUP_ID}</id><name>${GROUP_NAME}</name><computer_additions><computer><name>${COMPUTERNAME}</name></computer></computer_additions></computer_group>"


curl -sSkiu ${apiuser}:${apipass} "${jssURL}/${GROUP_URL}" \
	-H "Content-Type: text/xml" \
	-d "${xmlHeader}${GROUP_Data}" \
	-X PUT  > /dev/null

# Update Jamf
#########################################################################################
sudo jamf recon
